const Keywords = ['utm_',
                  'wt_',
                  'refID',
                  'src',
                  'ext',
                  '_trk',
                  'mcID',
                  'tt_',
                  'eqrecqid',
                  'fbclid',
                  'yclid',
                  'gclid',
                  'wc_mc',
                  'amp',
                  'clickin',
                  'AffiliateID',
                  'campid',
                  'pf_rd',
                  'hmb_',
                  'igshid',
                  'fbid',
                  'algo_',
                  'spm',
                  'btsid',
                  'ws_ab_',
                  'pgtype',
                  'cid',
                  'sclid',
                  'key-sofort_',
                  'campaign',
                  'awc',
                  'partner',
                  'zanpid',
                  '_branch_match_id'];

const deleted_Keywords = ['action',
                          'service',
                          'module'];